---
title: "Convert coordinate in MSF"
author: "Jean-Francois Chartier"
date: "14 mars 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(magrittr)
```


#Read MSF data
```{r}
MSF.data=read.csv("MSF_data.csv", stringsAsFactors = F, encoding = "UTF-8", blank.lines.skip = T)

```

#declare functions
```{r}

function1<-function(coor){
  split.coor= strsplit(coor, split = "E", fixed = T)[[1]]
  #str(split.coor)
  #degreeN=substr(split.coor[1], 3, 4)
  degreeN=stringr::str_match(split.coor[1], pattern = "N (.*?)° ")[,2]
  #print(degreeN)
  minN = stringr::str_match(split.coor[1], pattern = "° (.*?)' ")[,2]
  #print(minN)
  secN = stringr::str_match(split.coor[1], pattern = "' (.*?)''")[,2]
  #print(secN)
  
  #degreeE=substr(split.coor[2], 2, 3)
  #print(split.coor[2])
  degreeE = stringr::str_match(split.coor[2], pattern = " (.*?)° ")[,2]
  minE = stringr::str_match(split.coor[2], pattern = "° (.*?)' ")[,2]
  secE = stringr::str_match(split.coor[2], pattern = "' (.*?)''")[,2]
  coorN=paste(degreeN,minN, secN, sep = " ")
  coorE=paste(degreeE,minE, secE, sep = " ")
  
  return(paste(coorN, coorE, sep = ";"))
}

function2<-function(coor){
  #library(glue)
  tag1="'"
  tag2="''"
  if(grepl(pattern = "’", x = coor)){
    tag1="’"
  }
  if(grepl(pattern = "”", x = coor)){
    tag2="”"
  }
  if(grepl(pattern = "’", x = coor)){
    tag1="’"
  }
  if(grepl(pattern = '"', x = coor)){
    tag2='"'
  }
  
  
  
  split.coor= strsplit(coor, split = "N", fixed = T)[[1]]
  split.coor=trimws(split.coor)
  
  degreeN=substr(split.coor[1], 0, stringr::str_locate(split.coor[1], pattern = "°")[1]-1) %>%trimws(.)
  minN = stringr::str_match(split.coor[1], pattern = paste0("°(.*?)", tag1))[,2]%>%trimws(.)
  #print(minN)
  secN = stringr::str_match(split.coor[1], pattern = paste0(tag1, "(.*?)", tag2))[,2]%>%trimws(.)
  if (is.na(secN)){
    secN="0"
  }
  
  degreeE=substr(split.coor[2], start = stringr::str_locate(split.coor[2], pattern = "°")[1]-3, stop = stringr::str_locate(split.coor[2], pattern = "°")[1]-1)%>%trimws(.)
  
  minE=stringr::str_match(split.coor[2], pattern = paste0("°(.*?)", tag1))[,2]%>%trimws(.)
  
  #minE = substr(split.coor[2], start = stringr::str_locate(split.coor[2], pattern = "°")[1]+1, stop = stringr::str_locate(split.coor[2], pattern = "°")[1]-1)
  
  secE = stringr::str_match(split.coor[2], pattern = paste0(tag1, "(.*?)", tag2))[,2]%>%trimws(.)
  if (is.na(secE)){
    secE="0"
  }
  
  coorN=paste(degreeN,minN, secN, sep = " ")
  coorE=paste(degreeE,minE, secE, sep = " ")
  return(paste(coorN, coorE, sep = ";"))
  
}

function3<-function(coor, split){
  split.coor= strsplit(coor, split = split, fixed = T)[[1]]
  x <- stringr::str_extract_all(split.coor[1],"\\(?[0-9,.]+\\)?")[[1]]
  #print(x)
  degreeN=x[1]
  minN=x[2]
  secN=ifelse(length(x)<3, 0, x[3])
  
  y=stringr::str_extract_all(split.coor[2],"\\(?[0-9,.]+\\)?")[[1]]
  #print(y)
  degreeE=y[1]
  minE=y[2]
  secE=ifelse(length(x)<3, 0, y[3])
  
  coorN=paste(degreeN,minN, secN, sep = " ")
  coorE=paste(degreeE,minE, secE, sep = " ")
  return(paste(coorN, coorE, sep = ";"))
}

  
```

#extract coordinates
```{r}
sapply(1:length(MSF.data$Coord.Geo..DMS.), function(i){
  #print(i)
  coor=MSF.data$Coord.Geo..DMS.[i]
  
  newCoor=NA
  if ((MSF.data$Coord.Geo..DMS.[i]!="Coordonnées inconnues") & (MSF.data$Coord.Geo..DMS.[i]!="State")){
    #print(coor)
    if (grepl("geonames", MSF.data$Source[i]) & substr(coor, 1, 1)=="N"){
      newCoor=function1(coor)
      #print(newCoor)
    } else if (grepl("Position donnée par MSF", MSF.data$Source[i]) & substr(coor, nchar(coor), nchar(coor))=="E"){
      newCoor=function2(coor)
      #print(newCoor)
    } else if(grepl("Position donnée par MSF", MSF.data$Source[i]) & substr(coor, 1, 1)=="N"){
      #print(i)
      newCoor=function3(coor, "E")
      #print(newCoor)
    } else if (grepl("Validé Google Earth", MSF.data$Source[i]) & grepl("N,",coor)){
      #print(i)
      newCoor=function3(coor, "N,")
      #print(newCoor)
    } else if (grepl("Open Street Map", MSF.data$Source[i]) & grepl("N  ",coor)){
      #print(i)
      newCoor=function3(coor, "N  ")
      #print(newCoor)
    }
    
  }
  newCoor
})->newCoords

newCoords=stringr::str_replace_all(newCoords, pattern = ",", replacement = ".")
```

#Convert coordinates into lat and long
```{r}
lapply(newCoords, function(coor){
  lat=NA
  long=NA
  if (is.na(coor)==F)
  {
    coor=strsplit(coor, split = ";")[[1]]
    
    lat=coor[1]
    print(lat)
    lat=strsplit(lat, split = " ")[[1]]
    print(lat)
    lat=as.numeric(lat)
    lat=paste((lat[1]+(lat[2]/60) +(lat[3]/3600)), sep = ".")
    print(lat)
    
    long=coor[2]
    print(long)
    long=strsplit(long, split = " ")[[1]]
    print(long)
    long=as.numeric(long)
    long=paste((long[1]+(long[2]/60) +(long[3]/3600)), sep = ".")
    print(long)
  }
  data.frame(lat,long)
  
}) %>% data.table::rbindlist(.)->latAndLong
```

#add lat and long
```{r}
MSF.data$LATITUDE=latAndLong$lat
MSF.data$LONGITUDE=latAndLong$long
```
#save
```{r}
saveRDS(object = MSF.data, "MSF.data.rds")
```

